image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  FLUTTER_VERSION: "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail
  # flutter sdk setup
  - wget --output-document=flutter-sdk.tar.xz $FLUTTER_VERSION
  - tar -xf flutter-sdk.tar.xz
  - export PATH=$PATH:$PWD/flutter/bin
  - echo flutter.sdk=$PWD/flutter > android/local.properties
  # - chmod +x android/gradlew
  # 

stages:
  - build

build:apk:
  stage: build
  script:
    - touch .env.dev .env.prod
    - echo "master_key='$MASTER_KEY'" >> .env.dev
    - echo "app_id='$APP_ID'" >> .env.dev
    - echo "url='$URL'" >> .env.dev
    - echo "master_key='$MASTER_KEY'" >> .env.prod
    - echo "app_id='$APP_ID'" >> .env.prod
    - echo "url='$URL'" >> .env.prod
    - flutter build apk "--$BUILD_TYPE"
    - cp -R build/app/outputs/apk "$CI_PROJECT_NAME-$BUILD_TYPE-apk"
  artifacts:
    paths:
      - "$CI_PROJECT_NAME-$BUILD_TYPE-apk"
  only:
    - master
